version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - wordpress:/var/www/html
       - ./.uploads/:/var/www/html/wp-content/uploads/
       - ./theme/:/var/www/html/wp-content/themes/theme
       - ./.plugins/:/var/www/html/wp-content/plugins/
       - ./vendor/:/var/www/html/wp-content/vendor/
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: my_wordpress_db_password

   db:
     image: mysql:5.7
     volumes:
       - ./.data:/docker-entrypoint-initdb.d
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: my_db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: my_wordpress_db_password

   composer:
    image: composer/composer:php7
    command: update
    volumes:
      - .:/app

volumes:
    wordpress:
    db_data:
